apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-28T11:32:51Z
  generation: 1
  labels:
    run: fingonode
  name: fingonode
  namespace: default
  resourceVersion: "179907"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fingonode
  uid: 385881a0-514d-11e9-8337-005056963c38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: fingonode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fingonode
    spec:
      containers:
      - image: fingolfint/jx-node-http:v1
        imagePullPolicy: IfNotPresent
        name: fingonode
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-28T11:32:59Z
    lastUpdateTime: 2019-03-28T11:32:59Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-28T11:32:51Z
    lastUpdateTime: 2019-03-28T11:32:59Z
    message: ReplicaSet "fingonode-747d8dfc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
