apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: fingonode
  name: fingonode
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: fingonode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: fingonode
    spec:
      containers:
      - image: fingolfint/jx-node-http:v1
        imagePullPolicy: IfNotPresent
        name: fingonode
        ports:
        - containerPort: 8080
          protocol: TCP
