---
apiVersion: v1
kind: Service
metadata:
  namespace: noistio
  name: jx-node-http
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: fingonode
  type: LoadBalancer