apiVersion: v1
kind: Service
metadata:
  labels:
    run: fingonode
  name: fingonode
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: fingonode
  type: LoadBalancer
